/**
 * @file board_config.h
 * @brief Waveshare ESP32-P4-WIFI6-Touch-LCD-4.3-C board constants.
 */

#ifndef SPECTER_ESP32P4_LCD_4P3_BOARD_CONFIG_H_INCLUDED
#define SPECTER_ESP32P4_LCD_4P3_BOARD_CONFIG_H_INCLUDED

#include "driver/gpio.h"

#define SPECTER_BOARD_NAME "ESP32-P4-WIFI6-Touch-LCD-4.3-C"

#define SPECTER_LCD_WIDTH 480U
#define SPECTER_LCD_HEIGHT 800U
#define SPECTER_LCD_DPI_CLOCK_MHZ 30U
#define SPECTER_LCD_DSI_LANES 2U
#define SPECTER_LCD_DSI_LANE_BITRATE_MBPS 500U
#define SPECTER_LCD_DSI_LDO_CHANNEL 3
#define SPECTER_LCD_DSI_LDO_MV 2500

#define SPECTER_LCD_HSYNC_BACK_PORCH 42U
#define SPECTER_LCD_HSYNC_PULSE_WIDTH 12U
#define SPECTER_LCD_HSYNC_FRONT_PORCH 42U
#define SPECTER_LCD_VSYNC_BACK_PORCH 2U
#define SPECTER_LCD_VSYNC_PULSE_WIDTH 8U
#define SPECTER_LCD_VSYNC_FRONT_PORCH 60U

#define SPECTER_LCD_RESET_GPIO GPIO_NUM_27
#define SPECTER_LCD_RESET_ACTIVE_HIGH false
#define SPECTER_LCD_BACKLIGHT_GPIO GPIO_NUM_26
#define SPECTER_LCD_BACKLIGHT_INVERTED true

#define SPECTER_TOUCH_I2C_PORT 1
#define SPECTER_TOUCH_I2C_SCL_GPIO GPIO_NUM_8
#define SPECTER_TOUCH_I2C_SDA_GPIO GPIO_NUM_7
#define SPECTER_TOUCH_I2C_FREQUENCY_HZ 400000U
#define SPECTER_TOUCH_RESET_GPIO GPIO_NUM_23
#define SPECTER_TOUCH_HAS_RESET 1
#define SPECTER_TOUCH_INTERRUPT_GPIO GPIO_NUM_NC
#define SPECTER_TOUCH_GT911_ADDRESS 0x5dU
#define SPECTER_TOUCH_GT911_BACKUP_ADDRESS 0x14U

#define SPECTER_SDMMC_D0_GPIO GPIO_NUM_39
#define SPECTER_SDMMC_D1_GPIO GPIO_NUM_40
#define SPECTER_SDMMC_D2_GPIO GPIO_NUM_41
#define SPECTER_SDMMC_D3_GPIO GPIO_NUM_42
#define SPECTER_SDMMC_CLK_GPIO GPIO_NUM_43
#define SPECTER_SDMMC_CMD_GPIO GPIO_NUM_44

#endif  // SPECTER_ESP32P4_LCD_4P3_BOARD_CONFIG_H_INCLUDED
